### ISSUE TITLE
sudo false on travis

### ISSUE THREAD

**Issue by rowanc1** [3ptscience/git-project#26]

**Comment by bsmithyman** [comment]
Setting `sudo: false` allows Travis to run this in their container-based architecture, which is faster and more stable.

**Comment by mfirmin** [comment]
Right. I meant to ask, @rowanc1. What is the bug here?

**Comment by bsmithyman** [comment]
That it says `sudo: true` :)

**Comment by mfirmin** [comment]
aaah. didn't realize it had sudo true

**Comment by mfirmin** [comment]
Closed by #29
